<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Setup" data-toc-modified-id="Setup-0.1"><span class="toc-item-num">0.1&nbsp;&nbsp;</span>Setup</a></span></li><li><span><a href="#3-char-model" data-toc-modified-id="3-char-model-0.2"><span class="toc-item-num">0.2&nbsp;&nbsp;</span>3 char model</a></span><ul class="toc-item"><li><span><a href="#Create-inputs" data-toc-modified-id="Create-inputs-0.2.1"><span class="toc-item-num">0.2.1&nbsp;&nbsp;</span>Create inputs</a></span></li><li><span><a href="#Create-and-train-model" data-toc-modified-id="Create-and-train-model-0.2.2"><span class="toc-item-num">0.2.2&nbsp;&nbsp;</span>Create and train model</a></span></li><li><span><a href="#Test-model" data-toc-modified-id="Test-model-0.2.3"><span class="toc-item-num">0.2.3&nbsp;&nbsp;</span>Test model</a></span></li></ul></li><li><span><a href="#Our-first-RNN!" data-toc-modified-id="Our-first-RNN!-0.3"><span class="toc-item-num">0.3&nbsp;&nbsp;</span>Our first RNN!</a></span><ul class="toc-item"><li><span><a href="#Create-inputs" data-toc-modified-id="Create-inputs-0.3.1"><span class="toc-item-num">0.3.1&nbsp;&nbsp;</span>Create inputs</a></span></li><li><span><a href="#Create-and-train-model" data-toc-modified-id="Create-and-train-model-0.3.2"><span class="toc-item-num">0.3.2&nbsp;&nbsp;</span>Create and train model</a></span></li><li><span><a href="#Test-model" data-toc-modified-id="Test-model-0.3.3"><span class="toc-item-num">0.3.3&nbsp;&nbsp;</span>Test model</a></span></li></ul></li><li><span><a href="#Our-first-RNN-with-keras!" data-toc-modified-id="Our-first-RNN-with-keras!-0.4"><span class="toc-item-num">0.4&nbsp;&nbsp;</span>Our first RNN with keras!</a></span></li><li><span><a href="#Returning-sequences" data-toc-modified-id="Returning-sequences-0.5"><span class="toc-item-num">0.5&nbsp;&nbsp;</span>Returning sequences</a></span><ul class="toc-item"><li><span><a href="#Create-inputs" data-toc-modified-id="Create-inputs-0.5.1"><span class="toc-item-num">0.5.1&nbsp;&nbsp;</span>Create inputs</a></span></li><li><span><a href="#Create-and-train-model" data-toc-modified-id="Create-and-train-model-0.5.2"><span class="toc-item-num">0.5.2&nbsp;&nbsp;</span>Create and train model</a></span></li><li><span><a href="#Test-model" data-toc-modified-id="Test-model-0.5.3"><span class="toc-item-num">0.5.3&nbsp;&nbsp;</span>Test model</a></span></li><li><span><a href="#Sequence-model-with-keras" data-toc-modified-id="Sequence-model-with-keras-0.5.4"><span class="toc-item-num">0.5.4&nbsp;&nbsp;</span>Sequence model with keras</a></span></li><li><span><a href="#One-hot-sequence-model-with-keras" data-toc-modified-id="One-hot-sequence-model-with-keras-0.5.5"><span class="toc-item-num">0.5.5&nbsp;&nbsp;</span>One-hot sequence model with keras</a></span></li></ul></li><li><span><a href="#Stateful-model-with-keras" data-toc-modified-id="Stateful-model-with-keras-0.6"><span class="toc-item-num">0.6&nbsp;&nbsp;</span>Stateful model with keras</a></span></li><li><span><a href="#Pure-python-RNN!" data-toc-modified-id="Pure-python-RNN!-0.7"><span class="toc-item-num">0.7&nbsp;&nbsp;</span>Pure python RNN!</a></span><ul class="toc-item"><li><span><a href="#Set-up-basic-functions" data-toc-modified-id="Set-up-basic-functions-0.7.1"><span class="toc-item-num">0.7.1&nbsp;&nbsp;</span>Set up basic functions</a></span></li><li><span><a href="#Set-up-training" data-toc-modified-id="Set-up-training-0.7.2"><span class="toc-item-num">0.7.2&nbsp;&nbsp;</span>Set up training</a></span></li></ul></li><li><span><a href="#Keras-GRU" data-toc-modified-id="Keras-GRU-0.8"><span class="toc-item-num">0.8&nbsp;&nbsp;</span>Keras GRU</a></span><ul class="toc-item"><li><span><a href="#End" data-toc-modified-id="End-0.8.1"><span class="toc-item-num">0.8.1&nbsp;&nbsp;</span>End</a></span></li></ul></li></ul></li></ul></div>

In [1]:
%matplotlib inline
import utils
from utils import *
from __future__ import division, print_function

/anaconda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


## Setup

We're going to download the collected works of Nietzsche to use as our data for this class.

In [20]:
path = get_file('nietzsche.txt', origin="https://s3.amazonaws.com/text-datasets/nietzsche.txt")
text = open(path).read()
print('corpus length:', len(text))

corpus length: 600893


In [21]:
chars = sorted(list(set(text)))
vocab_size = len(chars)+1
print('total chars:', vocab_size)

total chars: 85


In [22]:
print(chars)

['\n', ' ', '!', '"', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'Æ', 'ä', 'æ', 'é', 'ë']


Sometimes it's useful to have a zero value in the dataset, e.g. for padding

In [23]:
chars.insert(0, "\0")

In [24]:
print(chars)

['\x00', '\n', ' ', '!', '"', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'Æ', 'ä', 'æ', 'é', 'ë']


In [25]:
print(chars[1:-6])

['\n', ' ', '!', '"', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y']


In [26]:
''.join(chars[1:-6])

'\n !"\'(),-.0123456789:;=?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_abcdefghijklmnopqrstuvwxy'

Map from chars to indices and back again

In [27]:
char_indices = dict((c, i) for i, c in enumerate(chars))
indices_char = dict((i, c) for i, c in enumerate(chars))

*idx* will be the data we use from now own - it simply converts all the characters to their index (based on the mapping above)

In [28]:
idx = [char_indices[c] for c in text] # 把这个文章全部转成数字表示的列表

In [29]:
len(idx)

600893

In [30]:
idx[:10]

[40, 42, 29, 30, 25, 27, 29, 1, 1, 1]

In [31]:
''.join(indices_char[i] for i in idx[:70])

'PREFACE\n\n\nSUPPOSING that Truth is a woman--what then? Is there not gro'

## 3 char model

### Create inputs

Create a list of every 4th character, starting at the 0th, 1st, 2nd, then 3rd characters

In [33]:
len(idx)

600893

In [37]:
a = 50

In [35]:
step = 3

In [44]:
for i in range(0,a-step-1,step):
    print(i,i+1,i+2,i+3)

0 1 2 3
3 4 5 6
6 7 8 9
9 10 11 12
12 13 14 15
15 16 17 18
18 19 20 21
21 22 23 24
24 25 26 27
27 28 29 30
30 31 32 33
33 34 35 36
36 37 38 39
39 40 41 42
42 43 44 45
45 46 47 48


In [48]:
idx[:10]

[40, 42, 29, 30, 25, 27, 29, 1, 1, 1]

In [49]:
c1_dat = [idx[i] for i in range(0,len(idx)-step,step)]
c2_dat = [idx[i+1] for i in range(0,len(idx)-step,step)]
c3_dat = [idx[i+2] for i in range(0,len(idx)-step,step)]
c4_dat = [idx[i+3] for i in range(0,len(idx)-step,step)]

In [51]:
c1_dat[:10]

[40, 30, 29, 1, 40, 43, 31, 61, 2, 74]

In [54]:
c1_dat[-10:]

[72, 61, 62, 62, 73, 67, 68, 72, 59, 67]

我们的输入：

In [65]:
x1 = np.stack(c1_dat[:-2]) # 为什么使用到-2的序列呢？
x2 = np.stack(c2_dat[:-2])
x3 = np.stack(c3_dat[:-2])

用x1，x2，x3组成的3个序列预测下一个单词序列x4

输出：

In [66]:
y = np.stack(c4_dat[:-2])

对比一下原始idx：

In [71]:
idx[:20]

[40, 42, 29, 30, 25, 27, 29, 1, 1, 1, 43, 45, 40, 40, 39, 43, 33, 38, 31, 2]

看看看前10个输入和输出：

In [67]:
x1[:10],x2[:10],x3[:10]

(array([40, 30, 29,  1, 40, 43, 31, 61,  2, 74]),
 array([42, 25,  1, 43, 40, 33,  2, 54, 44, 73]),
 array([29, 27,  1, 45, 39, 38, 73, 73, 71, 61]))

In [70]:
y[:15]

array([30, 29,  1, 40, 43, 31, 61,  2, 74,  2,  2, 76, 54,  9, 54])

这里就能看出来`step`变量的意思了，就是用3个字符去预测第四个字符：

```
序列：40 42 29 预测  30
序列：30 25 27 预测  29
序列：29  1  1 预测   1
...
...
```

In [73]:
x1.shape,y.shape

((200295,), (200295,))

The number of latent factors to create (i.e. the size of the embedding matrix)

嵌入矩阵的维度

In [75]:
embedding_size = 42 #词向量，嵌入矩阵的维度

In [91]:
def embedding_input(name,n_inputs,n_outputs):
    inputs = Input(shape=(1,),dtype='int64',name=name)
    emb = Embedding(input_dim=n_inputs,output_dim=n_outputs,input_length=1)(inputs)
    return inputs,Flatten()(emb)


Create inputs and embedding outputs for each of our 3 character inputs

作者认为嵌入矩阵比one-hot更好，所以这里第一个模型并没有使用Rnn，而是嵌入模型

In [92]:
c1_in,c1 = embedding_input('c1',vocab_size,embedding_size)
c2_in,c2 = embedding_input('c2',vocab_size,embedding_size)
c3_in,c3 = embedding_input('c3',vocab_size,embedding_size)

### Create and train model

Pick a size for our hidden state

In [93]:
n_hidden = 256

This is the 'green arrow' from our diagram - the layer operation from input to hidden.

In [94]:
dense_in = Dense(n_hidden, activation='relu')

Our first hidden activation is simply this function applied to the result of the embedding of the first character.

In [95]:
c1_hidden = dense_in(c1)

This is the 'orange arrow' from our diagram - the layer operation from hidden to hidden.

In [96]:
dense_hidden = Dense(n_hidden, activation='tanh')

Our second and third hidden activations sum up the previous hidden state (after applying dense_hidden) to the new input state.

In [97]:
c2_dense = dense_in(c2)
hidden_2 = dense_hidden(c1_hidden)
c2_hidden = keras.layers.add([c2_dense, hidden_2])

In [98]:
c3_dense = dense_in(c3)
hidden_3 = dense_hidden(c2_hidden)
c3_hidden =keras.layers.add([c3_dense, hidden_3])

This is the 'blue arrow' from our diagram - the layer operation from hidden to output.

In [99]:
dense_out = Dense(vocab_size, activation='softmax') # 最终输出为所有字符可能性的概率，所以用softmax

The third hidden state is the input to our output layer.

In [100]:
c4_out = dense_out(c3_hidden)

In [101]:
model = Model([c1_in, c2_in, c3_in], c4_out)

In [102]:
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam()) # 没有one-hot就用这个

Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [103]:
model.optimizer.lr=0.000001

In [104]:
model.fit([x1, x2, x3], y, batch_size=64, epochs=4)

Epoch 1/4
200295/200295 [==============================] - 9s 46us/step - loss: 4.4043
Epoch 2/4
200295/200295 [==============================] - 9s 44us/step - loss: 4.2851
Epoch 3/4
200295/200295 [==============================] - 9s 44us/step - loss: 4.0334
Epoch 4/4
200295/200295 [==============================] - 11s 54us/step - loss: 3.6511


In [105]:
model.optimizer.lr=0.01

In [106]:
model.fit([x1, x2, x3], y, batch_size=64, epochs=4)

Epoch 1/4
200295/200295 [==============================] - 10s 50us/step - loss: 3.3382
Epoch 2/4
200295/200295 [==============================] - 10s 48us/step - loss: 3.2028
Epoch 3/4
200295/200295 [==============================] - 10s 50us/step - loss: 3.1475
Epoch 4/4
200295/200295 [==============================] - 12s 61us/step - loss: 3.1204


In [108]:
model.optimizer.lr = 0.000001

In [109]:
model.fit([x1, x2, x3], y, batch_size=64, epochs=4)

Epoch 1/4
200295/200295 [==============================] - 10s 51us/step - loss: 3.1033
Epoch 2/4
200295/200295 [==============================] - 10s 51us/step - loss: 3.0906
Epoch 3/4
200295/200295 [==============================] - 10s 49us/step - loss: 3.0805
Epoch 4/4
200295/200295 [==============================] - 11s 55us/step - loss: 3.0718


In [110]:
model.optimizer.lr = 0.01

In [111]:
model.fit([x1, x2, x3], y, batch_size=64, epochs=4)

Epoch 1/4
200295/200295 [==============================] - 10s 51us/step - loss: 3.0640
Epoch 2/4
200295/200295 [==============================] - 10s 48us/step - loss: 3.0566
Epoch 3/4
200295/200295 [==============================] - 10s 48us/step - loss: 3.0492
Epoch 4/4
200295/200295 [==============================] - 10s 51us/step - loss: 3.0418


### Test model

测试模型效果，就是用`steps`个的字符预测下一个

In [112]:
[x1,x2,x3] # 用40 42 29 预测下一个

[array([40, 30, 29, ..., 67, 68, 72]),
 array([42, 25,  1, ..., 72, 59, 62]),
 array([29, 27,  1, ...,  2,  2, 67])]

In [133]:
def get_next(inputs):
    idxs = [char_indices[c] for c in inputs]
    arrs = [np.array(id)[np.newaxis] for id in idxs] # 添加新轴
    p = model.predict(arrs)
    i = np.argmax(p)
    print(i)
    return chars[i]

In [134]:
get_next(' th')

2


' '

In [128]:
def get_next(inp):
    idxs = [char_indices[c] for c in inp]
    arrs = [np.array(i)[np.newaxis] for i in idxs]
    p = model.predict(arrs)
    i = np.argmax(p)
    return chars[i]

In [129]:
get_next('phi')

' '

In [ ]:
get_next(' th')

In [ ]:
get_next(' an')

## Our first RNN!

### Create inputs

This is the size of our unrolled RNN.

In [171]:
steps=8

For each of 0 through 7, create a list of every 8th character with that starting point. These will be the 8 inputs to out model.


这次是8个字符组成的列表

In [271]:
c_in_dat = [[idx[i+n] for i in range(0,len(idx)-steps,steps)] for n in range(steps)]

In [173]:
len(c_in_dat) # 8个列表的字符

8

建立每个列表的下一个字符，用连续的8个字符，预测下一个字符是什么

Then create a list of the next character in each of these series. This will be the labels for our model.

In [263]:
c_out_dat = [idx[i+steps] for i in range(0, len(idx)-steps,steps)]

In [264]:
len(c_out_dat)

75111

In [265]:
xs = [np.stack(c[:-2]) for c in c_in_dat] 

In [266]:
len(xs), xs[0].shape

(8, (75109,))

In [176]:
y = np.stack(c_out_dat[:-2])

In [177]:
y.shape

(75109,)

So each column below is one series of 8 characters from the text.

In [178]:
[xs[n][:steps] for n in range(steps)]

[array([40,  1, 33,  2, 72, 67, 73,  2]),
 array([42,  1, 38, 44,  2,  9, 61, 73]),
 array([29, 43, 31, 71, 54,  9, 58, 61]),
 array([30, 45,  2, 74,  2, 76, 67, 58]),
 array([25, 40, 73, 73, 76, 61, 24, 71]),
 array([27, 40, 61, 61, 68, 54,  2, 58]),
 array([29, 39, 54,  2, 66, 73, 33,  2]),
 array([ 1, 43, 73, 62, 54,  2, 72, 67])]

...and this is the next character after each sequence.

In [179]:
y[:steps]

array([ 1, 33,  2, 72, 67, 73,  2, 68])

In [180]:
embedding_size = 42

### Create and train model

In [153]:
def embedding_input(name, n_in, n_out):
    inp = Input(shape=(1,), dtype='int64', name=name+'_in')
    emb = Embedding(n_in, n_out, input_length=1, name=name+'_emb')(inp)
    return inp, Flatten()(emb)

In [181]:
c_ins = [embedding_input('c'+str(n), vocab_size, embedding_size) for n in range(steps)]

In [182]:
n_hidden = 256

In [183]:
dense_in = Dense(n_hidden, activation='relu')
dense_hidden = Dense(n_hidden, activation='relu', kernel_initializer='identity') # 生成单位矩阵的初始化器。
dense_out = Dense(vocab_size, activation='softmax')

In [187]:
c_ins[0][1]

<tf.Tensor 'flatten_15/Reshape:0' shape=(?, ?) dtype=float32>

The first character of each sequence goes through dense_in(), to create our first hidden activations.

In [188]:
hidden = dense_in(c_ins[0][1])

Then for each successive layer we combine the output of dense_in() on the next character with the output of dense_hidden() on the current hidden state, to create the new hidden state.

In [191]:
for i in range(1,steps):
    c_dense = dense_in(c_ins[i][1])
    hidden = dense_hidden(hidden)
    hidden = keras.layers.add([c_dense, hidden])

Putting the final hidden state through dense_out() gives us our output.

In [192]:
c_out = dense_out(hidden)

So now we can create our model.

In [193]:
model = Model([c[0] for c in c_ins], c_out)
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam())

In [194]:
model.fit(xs, y, batch_size=64, epochs=12)

Epoch 1/12
75109/75109 [==============================] - 11s 140us/step - loss: 2.4681
Epoch 2/12
75109/75109 [==============================] - 10s 132us/step - loss: 2.1030
Epoch 3/12
75109/75109 [==============================] - 10s 135us/step - loss: 1.9602
Epoch 4/12
75109/75109 [==============================] - 11s 153us/step - loss: 1.8720
Epoch 5/12
75109/75109 [==============================] - 11s 148us/step - loss: 1.8092
Epoch 6/12
75109/75109 [==============================] - 11s 142us/step - loss: 1.7560
Epoch 7/12
75109/75109 [==============================] - 11s 145us/step - loss: 1.7145
Epoch 8/12
75109/75109 [==============================] - 10s 137us/step - loss: 1.6801
Epoch 9/12
75109/75109 [==============================] - 11s 144us/step - loss: 1.6513
Epoch 10/12
75109/75109 [==============================] - 11s 141us/step - loss: 1.6278
Epoch 11/12
75109/75109 [==============================] - 11s 142us/step - loss: 1.6065
Epoch 12/12
75109/75109 [=====

### Test model

In [195]:
def get_next(inp):
    idxs = [np.array(char_indices[c])[np.newaxis] for c in inp]
    p = model.predict(idxs)
    return chars[np.argmax(p)]

In [196]:
get_next('for thos')

'e'

In [197]:
get_next('part of ')

't'

In [198]:
get_next('queens a')

'n'

## Our first RNN with keras!

In [199]:
n_neurons,n_embedding_size,n_steps,n_vocab_size = (256,42,8,86)

上面的代码很繁琐，现在用keras建立一个RNN：

In [204]:
model = Sequential([
    Embedding(input_dim=n_vocab_size,output_dim=n_embedding_size,input_length=n_steps),
    SimpleRNN(n_hidden, activation='relu', recurrent_initializer='identity'),# 返回输出序列中的最后一个输出
    Dense(n_vocab_size,activation='softmax'),
])

In [205]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, 8, 42)             3612      
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 256)               76544     
_________________________________________________________________
dense_16 (Dense)             (None, 86)                22102     
Total params: 102,258
Trainable params: 102,258
Non-trainable params: 0
_________________________________________________________________


In [206]:
model.compile(loss='sparse_categorical_crossentropy',optimizer=Adam())

In [274]:
[xs[n][:steps] for n in range(steps)]

[array([40,  1, 33,  2, 72, 67, 73,  2]),
 array([42,  1, 38, 44,  2,  9, 61, 73]),
 array([29, 43, 31, 71, 54,  9, 58, 61]),
 array([30, 45,  2, 74,  2, 76, 67, 58]),
 array([25, 40, 73, 73, 76, 61, 24, 71]),
 array([27, 40, 61, 61, 68, 54,  2, 58]),
 array([29, 39, 54,  2, 66, 73, 33,  2]),
 array([ 1, 43, 73, 62, 54,  2, 72, 67])]

In [276]:
idx[:10]

[40, 42, 29, 30, 25, 27, 29, 1, 1, 1]

In [230]:
np.concatenate(xs,axis=1).shape

(75109, 8)

In [268]:
y

array([ 1, 33,  2, ..., 71, 61, 54])

In [213]:
model.fit(np.concatenate(xs,axis=1), y, batch_size=64, epochs=8)

Epoch 1/8
75109/75109 [==============================] - 7s 91us/step - loss: 2.7876
Epoch 2/8
75109/75109 [==============================] - 6s 85us/step - loss: 2.2878
Epoch 3/8
75109/75109 [==============================] - 7s 88us/step - loss: 2.0763
Epoch 4/8
75109/75109 [==============================] - 7s 91us/step - loss: 1.9423
Epoch 5/8
75109/75109 [==============================] - 7s 95us/step - loss: 1.8398
Epoch 6/8
75109/75109 [==============================] - 7s 94us/step - loss: 1.7565
Epoch 7/8
75109/75109 [==============================] - 7s 95us/step - loss: 1.6886
Epoch 8/8
75109/75109 [==============================] - 7s 95us/step - loss: 1.6319


In [239]:
def get_next_keras(inputs):
    idxs = [char_indices[c] for c in inputs]
    print(np.array(idxs).shape)
    arrs = np.array(idxs)[np.newaxis,:] # 增加一个维度,
    print(arrs)
    print(arrs.shape)
    p = model.predict(arrs)[0]
    print(p)
    return chars[np.argmax(p)]

In [240]:
get_next_keras('this is ')

(8,)
[[73 61 62 72  2 62 72  2]]
(1, 8)
[2.0987e-09 8.1168e-05 1.3563e-04 3.6383e-06 1.5258e-02 1.8692e-04 6.1778e-04 1.5158e-07 1.5179e-05
 5.6184e-05 4.1989e-06 2.8097e-09 4.5358e-06 2.4754e-06 5.3849e-08 9.1944e-09 3.3219e-08 3.4420e-09
 2.5180e-08 5.6073e-09 5.6119e-09 1.4444e-06 1.5435e-05 1.6840e-06 1.3694e-06 8.8319e-04 7.1805e-04
 5.9802e-04 1.5086e-04 2.2508e-03 3.4102e-04 3.0112e-03 2.1637e-04 4.6189e-03 2.4312e-04 1.2876e-04
 2.4297e-04 1.5801e-04 1.4699e-03 1.7231e-04 4.0515e-04 2.6612e-05 2.2871e-04 1.7455e-03 1.1046e-03
 4.2073e-05 3.1220e-05 1.3625e-03 6.2138e-09 2.8852e-05 3.8335e-05 6.0117e-04 9.2110e-07 6.1395e-05
 1.9512e-01 1.1817e-02 2.5069e-02 3.4202e-02 3.7701e-02 1.4244e-02 2.8289e-02 2.4878e-02 4.9045e-02
 2.8309e-03 1.5036e-03 1.0588e-02 3.9511e-02 8.0798e-02 1.0617e-01 2.2640e-02 2.7670e-03 2.4166e-02
 6.1613e-02 1.5374e-01 1.1427e-02 3.6011e-03 2.0734e-02 4.1140e-05 2.0279e-04 3.6225e-05 6.7259e-10
 8.8927e-10 1.0885e-09 3.0808e-09 1.2711e-09 1.1859e-09]


'a'

In [241]:
get_next_keras('this is ')

(8,)
[[73 61 62 72  2 62 72  2]]
(1, 8)
[2.0987e-09 8.1168e-05 1.3563e-04 3.6383e-06 1.5258e-02 1.8692e-04 6.1778e-04 1.5158e-07 1.5179e-05
 5.6184e-05 4.1989e-06 2.8097e-09 4.5358e-06 2.4754e-06 5.3849e-08 9.1944e-09 3.3219e-08 3.4420e-09
 2.5180e-08 5.6073e-09 5.6119e-09 1.4444e-06 1.5435e-05 1.6840e-06 1.3694e-06 8.8319e-04 7.1805e-04
 5.9802e-04 1.5086e-04 2.2508e-03 3.4102e-04 3.0112e-03 2.1637e-04 4.6189e-03 2.4312e-04 1.2876e-04
 2.4297e-04 1.5801e-04 1.4699e-03 1.7231e-04 4.0515e-04 2.6612e-05 2.2871e-04 1.7455e-03 1.1046e-03
 4.2073e-05 3.1220e-05 1.3625e-03 6.2138e-09 2.8852e-05 3.8335e-05 6.0117e-04 9.2110e-07 6.1395e-05
 1.9512e-01 1.1817e-02 2.5069e-02 3.4202e-02 3.7701e-02 1.4244e-02 2.8289e-02 2.4878e-02 4.9045e-02
 2.8309e-03 1.5036e-03 1.0588e-02 3.9511e-02 8.0798e-02 1.0617e-01 2.2640e-02 2.7670e-03 2.4166e-02
 6.1613e-02 1.5374e-01 1.1427e-02 3.6011e-03 2.0734e-02 4.1140e-05 2.0279e-04 3.6225e-05 6.7259e-10
 8.8927e-10 1.0885e-09 3.0808e-09 1.2711e-09 1.1859e-09]


'a'

In [242]:
get_next_keras('part of ')

(8,)
[[69 54 71 73  2 68 59  2]]
(1, 8)
[8.2187e-09 5.8026e-04 9.2926e-04 3.4386e-05 3.3459e-02 1.4342e-03 2.0816e-03 1.4778e-06 1.2096e-04
 1.9215e-04 3.6989e-05 3.9586e-08 4.7374e-06 3.3759e-06 2.6419e-07 4.1913e-08 9.0140e-08 3.8163e-08
 8.1401e-08 1.5576e-08 2.3906e-08 1.3316e-05 8.0024e-05 3.4936e-05 7.3617e-06 2.8078e-03 6.7438e-04
 2.7201e-03 3.2013e-03 7.1674e-03 2.4548e-03 9.5419e-03 2.7510e-03 5.2525e-03 1.9184e-03 3.7791e-03
 8.7208e-04 5.4042e-03 4.8628e-03 7.0337e-04 1.2924e-02 6.2227e-05 5.9044e-03 5.1895e-03 3.0460e-03
 6.3558e-04 1.6331e-04 4.9017e-04 8.4811e-08 1.8959e-04 1.3069e-04 1.0382e-03 5.4056e-06 6.1013e-04
 9.3949e-02 1.6636e-02 3.2580e-02 3.9180e-02 2.8433e-02 2.2568e-02 2.1035e-02 4.4850e-02 3.8516e-02
 7.9572e-03 8.6673e-03 3.1657e-02 6.1119e-02 3.3079e-02 2.9928e-02 4.4933e-02 2.5665e-03 1.8533e-02
 6.5488e-02 1.8345e-01 1.5948e-02 6.7977e-03 2.5297e-02 3.8842e-05 3.2337e-03 4.6585e-05 1.0087e-08
 2.9761e-09 9.2532e-09 1.4575e-08 5.7410e-09 4.4751e-09]


't'

In [243]:
get_next_keras('queens a')

(8,)
[[70 74 58 58 67 72  2 54]]
(1, 8)
[3.4078e-09 6.5984e-03 7.3305e-02 8.3061e-10 1.1112e-06 5.6375e-06 9.3404e-09 1.0714e-07 1.7822e-07
 9.2891e-08 3.1400e-05 2.2487e-07 2.7052e-06 7.0994e-07 2.8932e-07 1.0673e-07 5.2503e-07 4.6990e-08
 1.6111e-07 9.3355e-07 5.7841e-08 1.7544e-07 2.0557e-09 1.5411e-11 5.2271e-11 6.4335e-07 1.8324e-05
 2.5570e-06 7.9693e-07 2.8595e-07 3.5352e-06 3.2068e-05 1.6707e-08 1.1499e-06 5.2706e-11 6.0407e-09
 1.8817e-04 4.7437e-09 7.5521e-05 7.6737e-07 2.2070e-07 5.2775e-11 5.9308e-06 6.9094e-06 2.3763e-05
 1.4466e-06 1.2106e-06 1.9744e-05 8.9246e-07 4.4075e-14 1.2066e-09 9.0713e-07 5.7986e-10 4.5425e-13
 5.9627e-04 1.4062e-02 4.2142e-03 8.9712e-03 2.0150e-05 5.8722e-03 3.3966e-03 8.4707e-06 8.5070e-04
 5.8295e-05 4.5522e-05 7.1169e-02 8.6593e-03 6.1803e-01 9.2416e-05 9.4931e-03 3.1735e-05 4.0547e-02
 9.1248e-02 2.9331e-02 4.0976e-03 3.8248e-04 8.1728e-03 6.8405e-05 2.4772e-04 9.3387e-09 1.9939e-09
 3.7160e-11 3.2538e-09 3.5619e-09 2.2962e-09 2.1528e-09]


'n'

In [244]:
get_next_keras('I love y')

(8,)
[[33  2 65 68 75 58  2 78]]
(1, 8)
[5.1963e-07 8.0523e-04 3.4630e-03 1.6245e-05 6.1800e-05 1.2748e-04 4.5956e-09 2.9761e-06 4.7785e-04
 9.7734e-06 1.1785e-03 9.8601e-08 1.2063e-07 6.0159e-07 1.1917e-07 6.1271e-08 1.1036e-07 1.6412e-08
 3.8853e-07 1.0823e-07 2.5283e-07 1.9388e-05 3.5559e-05 5.5619e-07 1.1161e-07 3.6934e-04 3.1068e-04
 4.9740e-05 8.5291e-06 1.8986e-04 6.0927e-05 3.9267e-05 1.5052e-04 4.5257e-04 1.9705e-09 2.1305e-06
 1.1199e-06 1.8180e-06 4.1200e-05 5.5080e-05 1.9767e-06 2.9223e-09 4.8283e-05 4.3521e-04 4.4878e-04
 6.6762e-05 1.7186e-07 1.0171e-04 3.8496e-06 4.1315e-08 5.7986e-08 1.4364e-07 4.8128e-07 3.5090e-08
 6.0861e-02 7.8879e-03 1.0468e-02 1.7668e-03 2.3783e-01 1.0109e-02 7.9177e-03 5.6125e-02 2.6047e-02
 2.6273e-06 6.5020e-05 5.9567e-02 1.0553e-02 2.5278e-02 2.7744e-01 8.3595e-02 1.0651e-03 8.8575e-03
 1.3674e-03 5.4139e-02 1.4499e-02 3.8978e-03 1.7441e-02 1.1736e-03 1.3007e-02 3.9263e-07 6.6788e-07
 6.9607e-07 6.7733e-07 5.2088e-07 5.2049e-07 5.8114e-07]


'o'

## Returning sequences

### Create inputs

To use a sequence model, we can leave our input unchanged - but we have to change our output to a sequence (of course!)

Here, c_out_dat is identical to c_in_dat, but moved across 1 character.

In [248]:
#c_in_dat = [[idx[i+n] for i in xrange(0, len(idx)-1-cs, cs)]
#            for n in range(cs)]
c_out_dat = [[idx[i+n] for i in range(1, len(idx)-steps, steps)]  # 为什么？
            for n in range(steps)]

In [250]:
len(c_out_dat)

8

In [251]:
ys = [np.stack(c[:-2]) for c in c_out_dat]

Reading down each column shows one set of inputs and outputs.

In [253]:
print([xs[n][:steps] for n in range(steps)])

[array([[40],
       [ 1],
       [33],
       [ 2],
       [72],
       [67],
       [73],
       [ 2]]), array([[42],
       [ 1],
       [38],
       [44],
       [ 2],
       [ 9],
       [61],
       [73]]), array([[29],
       [43],
       [31],
       [71],
       [54],
       [ 9],
       [58],
       [61]]), array([[30],
       [45],
       [ 2],
       [74],
       [ 2],
       [76],
       [67],
       [58]]), array([[25],
       [40],
       [73],
       [73],
       [76],
       [61],
       [24],
       [71]]), array([[27],
       [40],
       [61],
       [61],
       [68],
       [54],
       [ 2],
       [58]]), array([[29],
       [39],
       [54],
       [ 2],
       [66],
       [73],
       [33],
       [ 2]]), array([[ 1],
       [43],
       [73],
       [62],
       [54],
       [ 2],
       [72],
       [67]])]


In [254]:
[ys[n][:steps] for n in range(steps)]

[array([42,  1, 38, 44,  2,  9, 61, 73]),
 array([29, 43, 31, 71, 54,  9, 58, 61]),
 array([30, 45,  2, 74,  2, 76, 67, 58]),
 array([25, 40, 73, 73, 76, 61, 24, 71]),
 array([27, 40, 61, 61, 68, 54,  2, 58]),
 array([29, 39, 54,  2, 66, 73, 33,  2]),
 array([ 1, 43, 73, 62, 54,  2, 72, 67]),
 array([ 1, 33,  2, 72, 67, 73,  2, 68])]

### Create and train model

In [255]:
dense_in = Dense(n_hidden, activation='relu')
dense_hidden = Dense(n_hidden, activation='relu', kernel_initializer='identity')
dense_out = Dense(vocab_size, activation='softmax', name='output')

We're going to pass a vector of all zeros as our starting point - here's our input layers for that:

In [256]:
inp1 = Input(shape=(embedding_size,), name='zeros')
hidden = dense_in(inp1)

In [259]:
outs = []

for i in range(n_steps):
    c_dense = dense_in(c_ins[i][1])
    hidden = dense_hidden(hidden)
    hidden = keras.layers.add([c_dense, hidden])
    # every layer now has an output
    outs.append(dense_out(hidden))

In [260]:
model = Model([inp1] + [c[0] for c in c_ins], outs)
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam())

In [262]:
zeros = np.tile(np.zeros(embedding_size), (len(xs[0]),1))
zeros.shape

(75109, 42)

In [ ]:
model.fit([zeros]+xs, ys, batch_size=64, nb_epoch=12)

### Test model

In [ ]:
def get_nexts(inp):
    idxs = [char_indices[c] for c in inp]
    arrs = [np.array(i)[np.newaxis] for i in idxs]
    p = model.predict([np.zeros(n_fac)[np.newaxis,:]] + arrs)
    print(list(inp))
    return [chars[np.argmax(o)] for o in p]

In [ ]:
get_nexts(' this is')

In [ ]:
get_nexts(' part of')

### Sequence model with keras

In [ ]:
n_hidden, n_fac, cs, vocab_size

To convert our previous keras model into a sequence model, simply add the 'return_sequences=True' parameter, and add TimeDistributed() around our dense layer.

In [ ]:
model=Sequential([
        Embedding(vocab_size, n_fac, input_length=cs),
        SimpleRNN(n_hidden, return_sequences=True, activation='relu', inner_init='identity'),
        TimeDistributed(Dense(vocab_size, activation='softmax')),
    ])

In [ ]:
model.summary()

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam())

In [ ]:
xs[0].shape

In [ ]:
x_rnn=np.stack(np.squeeze(xs), axis=1)
y_rnn=np.atleast_3d(np.stack(ys, axis=1))

In [ ]:
x_rnn.shape, y_rnn.shape

In [ ]:
model.fit(x_rnn, y_rnn, batch_size=64, nb_epoch=8)

In [ ]:
def get_nexts_keras(inp):
    idxs = [char_indices[c] for c in inp]
    arr = np.array(idxs)[np.newaxis,:]
    p = model.predict(arr)[0]
    print(list(inp))
    return [chars[np.argmax(o)] for o in p]

In [ ]:
get_nexts_keras(' this is')

### One-hot sequence model with keras

This is the keras version of the theano model that we're about to create.

In [ ]:
model=Sequential([
        SimpleRNN(n_hidden, return_sequences=True, input_shape=(cs, vocab_size),
                  activation='relu', inner_init='identity'),
        TimeDistributed(Dense(vocab_size, activation='softmax')),
    ])
model.compile(loss='categorical_crossentropy', optimizer=Adam())

In [ ]:
oh_ys = [to_categorical(o, vocab_size) for o in ys]
oh_y_rnn=np.stack(oh_ys, axis=1)

oh_xs = [to_categorical(o, vocab_size) for o in xs]
oh_x_rnn=np.stack(oh_xs, axis=1)

oh_x_rnn.shape, oh_y_rnn.shape

In [ ]:
model.fit(oh_x_rnn, oh_y_rnn, batch_size=64, nb_epoch=8)

In [ ]:
def get_nexts_oh(inp):
    idxs = np.array([char_indices[c] for c in inp])
    arr = to_categorical(idxs, vocab_size)
    p = model.predict(arr[np.newaxis,:])[0]
    print(list(inp))
    return [chars[np.argmax(o)] for o in p]

In [ ]:
get_nexts_oh(' this is')

## Stateful model with keras

In [ ]:
bs=64

A stateful model is easy to create (just add "stateful=True") but harder to train. We had to add batchnorm and use LSTM to get reasonable results.

When using stateful in keras, you have to also add 'batch_input_shape' to the first layer, and fix the batch size there.

In [ ]:
model=Sequential([
        Embedding(vocab_size, n_fac, input_length=cs, batch_input_shape=(bs,8)),
        BatchNormalization(),
        LSTM(n_hidden, return_sequences=True, stateful=True),
        TimeDistributed(Dense(vocab_size, activation='softmax')),
    ])

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam())

Since we're using a fixed batch shape, we have to ensure our inputs and outputs are a even multiple of the batch size.

In [ ]:
mx = len(x_rnn)//bs*bs

In [ ]:
model.fit(x_rnn[:mx], y_rnn[:mx], batch_size=bs, nb_epoch=4, shuffle=False)

In [ ]:
model.optimizer.lr=1e-4

In [ ]:
model.fit(x_rnn[:mx], y_rnn[:mx], batch_size=bs, nb_epoch=4, shuffle=False)

In [ ]:
model.fit(x_rnn[:mx], y_rnn[:mx], batch_size=bs, nb_epoch=4, shuffle=False)

## Pure python RNN!

### Set up basic functions

Now we're going to try to repeat the above theano RNN, using just pure python (and numpy). Which means, we have to do everything ourselves, including defining the basic functions of a neural net! Below are all of the definitions, along with tests to check that they give the same answers as theano. The functions ending in `_d` are the derivatives of each function.

In [ ]:
def sigmoid(x): return 1/(1+np.exp(-x))
def sigmoid_d(x): 
    output = sigmoid(x)
    return output*(1-output)

In [ ]:
def relu(x): return np.maximum(0., x)
def relu_d(x): return (x > 0.)*1.

In [ ]:
relu(np.array([3.,-3.])), relu_d(np.array([3.,-3.]))

In [ ]:
def dist(a,b): return pow(a-b,2)
def dist_d(a,b): return 2*(a-b)

In [ ]:
import pdb

In [ ]:
eps = 1e-7
def x_entropy(pred, actual): 
    return -np.sum(actual * np.log(np.clip(pred, eps, 1-eps)))
def x_entropy_d(pred, actual): return -actual/pred

In [ ]:
def softmax(x): return np.exp(x)/np.exp(x).sum()

In [ ]:
def softmax_d(x):
    sm = softmax(x)
    res = np.expand_dims(-sm,-1)*sm
    res[np.diag_indices_from(res)] = sm*(1-sm)
    return res

In [ ]:
test_preds = np.array([0.2,0.7,0.1])
test_actuals = np.array([0.,1.,0.])
nnet.categorical_crossentropy(test_preds, test_actuals).eval()

In [ ]:
x_entropy(test_preds, test_actuals)

In [ ]:
test_inp = T.dvector()
test_out = nnet.categorical_crossentropy(test_inp, test_actuals)
test_grad = theano.function([test_inp], T.grad(test_out, test_inp))

In [ ]:
test_grad(test_preds)

In [ ]:
x_entropy_d(test_preds, test_actuals)

In [ ]:
pre_pred = random(oh_x_rnn[0][0].shape)
preds = softmax(pre_pred)
actual = oh_x_rnn[0][0]

In [ ]:
np.allclose(softmax_d(pre_pred).dot(x_entropy_d(preds,actual)), preds-actual)

In [ ]:
softmax(test_preds)

In [ ]:
nnet.softmax(test_preds).eval()

In [ ]:
test_out = T.flatten(nnet.softmax(test_inp))

In [ ]:
test_grad = theano.function([test_inp], theano.gradient.jacobian(test_out, test_inp))

In [ ]:
test_grad(test_preds)

In [ ]:
softmax_d(test_preds)

In [ ]:
act=relu
act_d = relu_d

In [ ]:
loss=x_entropy
loss_d=x_entropy_d

We also have to define our own scan function. Since we're not worrying about running things in parallel, it's very simple to implement:

In [ ]:
def scan(fn, start, seq):
    res = []
    prev = start
    for s in seq:
        app = fn(prev, s)
        res.append(app)
        prev = app
    return res

...for instance, `scan` on `+` is the cumulative sum.

In [ ]:
scan(lambda prev,curr: prev+curr, 0, range(5))

### Set up training

Let's now build the functions to do the forward and backward passes of our RNN. First, define our data and shape.

In [ ]:
inp = oh_x_rnn
outp = oh_y_rnn
n_input = vocab_size
n_output = vocab_size

In [ ]:
inp.shape, outp.shape

Here's the function to do a single forward pass of an RNN, for a single character.

In [ ]:
def one_char(prev, item):
    # Previous state
    tot_loss, pre_hidden, pre_pred, hidden, ypred = prev
    # Current inputs and output
    x, y = item
    pre_hidden = np.dot(x,w_x) + np.dot(hidden,w_h)
    hidden = act(pre_hidden)
    pre_pred = np.dot(hidden,w_y)
    ypred = softmax(pre_pred)
    return (
        # Keep track of loss so we can report it
        tot_loss+loss(ypred, y),
        # Used in backprop
        pre_hidden, pre_pred, 
        # Used in next iteration
        hidden, 
        # To provide predictions
        ypred)

We use `scan` to apply the above to a whole sequence of characters.

In [ ]:
def get_chars(n): return zip(inp[n], outp[n])
def one_fwd(n): return scan(one_char, (0,0,0,np.zeros(n_hidden),0), get_chars(n))

Now we can define the backward step. We use a loop to go through every element of the sequence. The derivatives are applying the chain rule to each step, and accumulating the gradients across the sequence.

In [ ]:
# "Columnify" a vector
def col(x): return x[:,newaxis]

def one_bkwd(args, n):
    global w_x,w_y,w_h

    i=inp[n]  # 8x86
    o=outp[n] # 8x86
    d_pre_hidden = np.zeros(n_hidden) # 256
    for p in reversed(range(len(i))):
        totloss, pre_hidden, pre_pred, hidden, ypred = args[p]
        x=i[p] # 86
        y=o[p] # 86
        d_pre_pred = softmax_d(pre_pred).dot(loss_d(ypred,y))  # 86
        d_pre_hidden = (np.dot(d_pre_hidden, w_h.T) 
                        + np.dot(d_pre_pred,w_y.T)) * act_d(pre_hidden) # 256

        # d(loss)/d(w_y) = d(loss)/d(pre_pred) * d(pre_pred)/d(w_y)
        w_y -= col(hidden) * d_pre_pred * alpha
        # d(loss)/d(w_h) = d(loss)/d(pre_hidden[p-1]) * d(pre_hidden[p-1])/d(w_h)
        if (p>0): w_h -= args[p-1][3].dot(d_pre_hidden) * alpha
        w_x -= col(x)*d_pre_hidden * alpha
    return d_pre_hidden

Now we can set up our initial weight matrices. Note that we're not using bias at all in this example, in order to keep things simpler.

In [ ]:
scale=math.sqrt(2./n_input)
w_x = normal(scale=scale, size=(n_input,n_hidden))
w_y = normal(scale=scale, size=(n_hidden, n_output))
w_h = np.eye(n_hidden, dtype=np.float32)

Our loop looks much like the theano loop in the previous section, except that we have to call the backwards step ourselves.

In [ ]:
overallError=0
alpha=0.0001
for n in range(10000):
    res = one_fwd(n)
    overallError+=res[-1][0]
    deriv = one_bkwd(res, n)
    if(n % 1000 == 999):
        print ("Error:{:.4f}; Gradient:{:.5f}".format(
                overallError/1000, np.linalg.norm(deriv)))
        overallError=0

## Keras GRU

Identical to the last keras rnn, but a GRU!

In [ ]:
model=Sequential([
        GRU(n_hidden, return_sequences=True, input_shape=(cs, vocab_size),
                  activation='relu', inner_init='identity'),
        TimeDistributed(Dense(vocab_size, activation='softmax')),
    ])
model.compile(loss='categorical_crossentropy', optimizer=Adam())

In [ ]:
model.fit(oh_x_rnn, oh_y_rnn, batch_size=64, nb_epoch=8)

In [ ]:
get_nexts_oh(' this is')

### End